spring:
  profiles:
    active: dev

---
server:
  port: 8001
mybatis:
  type-aliases-package: classpath:com.yyh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 883203

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 
    prefer-ip-address: true 
info:
  app.name: yyh-springcloud
  company.name: blog.yyh.com

---
server:
  port: 8001
mybatis:
  type-aliases-package: classpath:com.yyh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud02?useUnicode=true&characterEncoding=utf8
    username: root
    password: 883203

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 
    prefer-ip-address: true 
info:
  app.name: yyh-springcloud
  company.name: blog.yyh.com